# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='count',
            unique_together=set([('title', 'name')]),
        ),
    ]
